apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  namespace: web
spec:
 containers:
 - name: mynginx
   image: nginx
   command: ["nginx"]
   args: ["-g", "daemon off;", "-q"]
   ports:
   - containerPort: 80
